Blog/Models/ErrorViewModel.cs
using System;

namespace Blog.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Blog/Models/Post.cs
namespace Blog.Models
{
    public class Post
    {
        public string Id { get; set; }
        
        public string UserId { get; set; }

        public User User { get; set; }

        public string Content { get; set; }
    }
}

Blog/Models/User.cs
using System.Collections.Generic;

namespace Blog.Models
{
    public class User
    {
        public string Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public List<Post> Posts { get; set; }
    }
}

Blog/Controllers/AuthorController.cs
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Data.Contexts;
using Blog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blog.Controllers
{
    public class AuthorController : Controller
    {
        private readonly BlogContext _context;

        public AuthorController(BlogContext context)
        {
            _context = context;
        }

        // GET
        public async Task<IActionResult> Index()
        {
            List<User> authors = await _context.Users.ToListAsync();

            return View(authors);
        }

        public async Task<IActionResult> Posts(string id)
        {
            IEnumerable<Post> query =
                from post in _context.Posts
                where post.UserId == id
                select post;
            
            dynamic myModel = new ExpandoObject();
            myModel.User = await _context.Users.FindAsync(id);
            myModel.Posts = query.ToList();

            return View(myModel);
            
        }
    }
}

Blog/Controllers/HomeController.cs
using System.Dynamic;
using System.Diagnostics;
using System.Threading.Tasks;
using Blog.Data.Contexts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Blog.Models;
using Microsoft.EntityFrameworkCore;

namespace Blog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly BlogContext _context;

        public HomeController(ILogger<HomeController> logger, BlogContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            dynamic myModel = new ExpandoObject();
            myModel.Users = await _context.Users.ToListAsync();
            myModel.Posts = await _context.Posts.ToListAsync();

            return View(myModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Blog/Views/Author/Index.cshtml
@model IEnumerable<Blog.Models.User>
@{
    ViewData["Title"] = "Authors";
}
<div class="text-center">
    @foreach (User user in Model)
    {
        <a asp-route-id=@user.Id asp-controller="Author" asp-action="Posts"><h1>@user.FirstName @user.LastName</h1></a>
    }
</div>

Blog/Views/Author/Posts.cshtml
@model dynamic
@{
    ViewData["Title"] = "Posts by";
}

<div class="text-left">
    <h1 class="text-info">@Model.User.FirstName @Model.User.LastName</h1>
    @foreach (Post post in Model.Posts)
    {
        <h2 class="font-italic">"@post.Content"</h2>
    }
</div>

Blog/Views/Home/Index.cshtml
@model dynamic
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    @foreach (User author in Model.Users)
    {
        <h1 class="text-info">@author.FirstName @author.LastName</h1>
        @foreach (Post post in Model.Posts)
        {
            if (post.UserId == author.Id)
            {
                <h2 class="font-italic">"@post.Content"</h2>
            }
        }
    }
</div>

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Blog
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>